apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rbd-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-ceph-block
---
apiVersion: v1
kind: Pod
metadata:
  name: block-test-pod
spec:
  containers:
  - name: test-container
    image: dockerhub.kubekey.local/library/busybox:latest
    command: ["/bin/sh", "-c", "sleep 3600"]
    volumeMounts:
    - mountPath: "/data"
      name: my-block-storage
  volumes:
  - name: my-block-storage
    persistentVolumeClaim:
      claimName: rbd-pvc 
