apiVersion: v1
kind: Service
metadata:
  name: rook-ceph-mon-a-external
  namespace: rook-ceph
spec:
  type: NodePort
  ports:
    - name: msgr1
      port: 6789
      targetPort: 6789
      protocol: TCP
    - name: msgr2
      port: 3300
      targetPort: 3300
      protocol: TCP
  selector:
    mon: a
    app: rook-ceph-mon

---

apiVersion: v1
kind: Service
metadata:
  name: rook-ceph-mon-b-external
  namespace: rook-ceph
spec:
  type: NodePort
  ports:
    - name: msgr1
      port: 6789
      targetPort: 6789
      protocol: TCP
    - name: msgr2
      port: 3300
      targetPort: 3300
      protocol: TCP
  selector:
    mon: b
    app: rook-ceph-mon

---

apiVersion: v1
kind: Service
metadata:
  name: rook-ceph-mon-c-external
  namespace: rook-ceph
spec:
  type: NodePort
  ports:
    - name: msgr1
      port: 6789
      targetPort: 6789
      protocol: TCP
    - name: msgr2
      port: 3300
      targetPort: 3300
      protocol: TCP
  selector:
    mon: c
    app: rook-ceph-mon

---

apiVersion: v1
kind: Service
metadata:
  name: rook-ceph-mgr-dashboard-external
  namespace: rook-ceph
spec:
  type: NodePort
  ports:
    - name: https-dashboard
      port: 8443
      targetPort: 8443
      protocol: TCP
  selector:
    app: rook-ceph-mgr
    rook_cluster: rook-ceph

---

apiVersion: v1
kind: Service
metadata:
  name: rook-ceph-mgr-external
  namespace: rook-ceph
spec:
  type: NodePort
  ports:
    - name: metrics
      port: 9283
      targetPort: 9283
      protocol: TCP
  selector:
    app: rook-ceph-mgr
    rook_cluster: rook-ceph

---

apiVersion: v1
kind: Service
metadata:
  name: rook-ceph-rgw-my-store-external
  namespace: rook-ceph
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: rook-ceph-rgw
    rgw: my-store
    rook_cluster: rook-ceph

---

apiVersion: v1
kind: Service
metadata:
  name: rook-ceph-exporter-external
  namespace: rook-ceph
spec:
  type: NodePort
  ports:
    - name: http-metrics
      port: 9926
      targetPort: 9926
      protocol: TCP
  selector:
    app: rook-ceph-exporter
    rook_cluster: rook-ceph
